name: plex-services
networks:
  networks_vlan_80:
    external: true
  networks_traefik_proxy:
    external: true

services:
  plex-movies:
    image: plexinc/pms-docker:plexpass
    container_name: plex-movies
    hostname: plex-movies
    restart: unless-stopped
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_MOVIES_CLAIM}
      - TZ=${TZ}
      - ALLOWED_NETWORKS=${PLEX_ALLOWED_NETWORKS}
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
      - HOSTNAME=plex-movies.${DOMAIN}
      - ROC_ENABLE_PRE_VEGA=1
    group_add:
      - "${RENDER_GROUP_ID}" # Change this to match your "render" host group id (getent group render)
      - "${VIDEO_GROUP_ID}" # Change this to match your "video" host group id (getent group video)
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/kfd:/dev/kfd # Remove this device if you don't use the OpenCL tone-mapping
    volumes:
      - ${APPDATA}/plex-movies/config:/config
      - ${APPDATA}/plex-movies/transcode:/transcode
      - ${MOVIES}:/media/movies:ro
    networks:
      networks_vlan_80:
        ipv4_address: ${PLEX_MOVIES_IP_ADDRESS}
      networks_traefik_proxy:
    dns:
      - ${METAL_DNS_IP_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex-movies.rule=Host(`plex-movies.${DOMAIN}`)
      - traefik.http.routers.plex-movies.tls.domains[0].main=dexome.com
      - traefik.http.routers.plex-movies.tls.domains[0].sans=*.dexome.com
      - traefik.http.routers.plex-movies.tls.certresolver=certificato
      - traefik.http.routers.plex-movies.entrypoints=web,web-secure
      - traefik.http.services.plex-movies.loadbalancer.server.port=32400
      - traefik.docker.network=networks_traefik_proxy
      - homepage.group=HeavyMetal
      - homepage.weight=2000
      - homepage.name=plex movies
      - homepage.icon=plex.png
      - homepage.href=https://plex-movies.${DOMAIN}/
      - homepage.description=for movies
      - homepage.widget.type=plex
      - homepage.widget.url=http://${PLEX_MOVIES_IP_ADDRESS}:32400
      - homepage.widget.key=${PLEX_MOVIES_TOKEN}
      - autoheal=true

  plex-tvshows:
    image: plexinc/pms-docker:plexpass
    container_name: plex-tvshows
    hostname: plex-tvshows
    restart: unless-stopped
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_TVSHOWS_CLAIM}
      - TZ=${TZ}
      - ALLOWED_NETWORKS=${PLEX_ALLOWED_NETWORKS}
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
      - HOSTNAME=plex-tvshows.${DOMAIN}
      - ROC_ENABLE_PRE_VEGA=1
    group_add:
      - "${RENDER_GROUP_ID}" # Change this to match your "render" host group id (getent group render)
      - "${VIDEO_GROUP_ID}" # Change this to match your "video" host group id (getent group video)
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/kfd:/dev/kfd # Remove this device if you don't use the OpenCL tone-mapping
    volumes:
      - ${APPDATA}/plex-tvshows/config:/config
      - ${APPDATA}/plex-tvshows/transcode:/transcode
      - ${TVSHOWS}:/media/tvshows:ro
    networks:
      networks_vlan_80:
        ipv4_address: ${PLEX_TVSHOWS_IP_ADDRESS}
      networks_traefik_proxy:
    dns:
      - ${METAL_DNS_IP_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex-tvshows.rule=Host(`plex-tvshows.${DOMAIN}`)
      - traefik.http.routers.plex-tvshows.tls.domains[0].main=dexome.com
      - traefik.http.routers.plex-tvshows.tls.domains[0].sans=*.dexome.com
      - traefik.http.routers.plex-tvshows.tls.certresolver=certificato
      - traefik.http.routers.plex-tvshows.entrypoints=web,web-secure
      - traefik.http.services.plex-tvshows.loadbalancer.server.port=32400
      - traefik.docker.network=networks_traefik_proxy
      - homepage.group=HeavyMetal
      - homepage.weight=2000
      - homepage.name=plex tvshows
      - homepage.icon=plex.png
      - homepage.href=https://plex-tvshows.${DOMAIN}/
      - homepage.description=for tvshows
      - homepage.widget.type=plex
      - homepage.widget.url=http://${PLEX_TVSHOWS_IP_ADDRESS}:32400
      - homepage.widget.key=${PLEX_TVSHOWS_TOKEN}
      - autoheal=true

  plex-music:
    image: plexinc/pms-docker:plexpass
    hostname: plex-music
    container_name: plex-music
    labels:
      traefik.enable: true
      traefik.http.routers.plex-music.rule: "Host(`music.${DOMAIN}`) || Host(`plex-music.${DOMAIN}`)"
      traefik.http.routers.plex-music.entrypoints: web,web-secure
      traefik.http.routers.plex-music.tls.certresolver: "certificato"
      traefik.http.services.plex-music.loadbalancer.server.port: 32400
      traefik.docker.network: networks_traefik_proxy
      homepage.group: Metal
      homepage.weight: 2000
      homepage.name: Plex
      homepage.icon: plex.png
      homepage.href: https://music.${DOMAIN}/
      homepage.description: for music
      homepage.widget.type: plex
      homepage.widget.url: http://${PLEXMUSIC_IP_ADDRESS}:32400
      homepage.widget.key: ${PLEX_MUSIC_TOKEN}
      autoheal: true
    networks:
      networks_traefik_proxy:
      networks_vlan_80:
        ipv4_address: ${PLEXMUSIC_IP_ADDRESS}
    dns:
      - ${METAL_DNS_IP_ADDRESS}
    environment:
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_MUSIC_CLAIM}
      - TZ=${TZ}
      - ALLOWED_NETWORKS=${PLEX_ALLOWED_NETWORKS}
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
      - HOSTNAME=music.${DOMAIN}
    volumes:
      - ${APPDATA}/plex-music/config:/config
      - ${MUSIC}:/media/music
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${PUID}:${PGID}
    group_add:
      - "${RENDER_GROUP_ID}" # Change this to match your "render" host group id (getent group render)
      - "${VIDEO_GROUP_ID}" # Change this to match your "video" host group id (getent group video)
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=https:/jellyfin.${DOMAIN}
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      # - /dev/kfd:/dev/kfd # Remove this device if you don't use the OpenCL tone-mapping
    volumes:
      - ${APPDATA}/jellyfin/config:/config
      - ${APPDATA}/jellyfin/transcode:/transcode
      - ${APPDATA}/jellyfin/cache:/cache
      - ${MOVIES}:/media/movies:ro
      - ${TVSHOWS}:/media/tvshows:ro
    networks:
      networks_vlan_80:
        ipv4_address: ${JELLYFIN_IP_ADDRESS}
      networks_traefik_proxy:
    dns:
      - ${METAL_DNS_IP_ADDRESS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)
      - traefik.http.routers.jellyfin.tls.domains[0].main=dexome.com
      - traefik.http.routers.jellyfin.tls.domains[0].sans=*.dexome.com
      - traefik.http.routers.jellyfin.tls.certresolver=certificato
      - traefik.http.routers.jellyfin.entrypoints=web,web-secure
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.docker.network=networks_traefik_proxy
      - autoheal=true
    restart: 'unless-stopped'
